In [198]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

import matplotlib.pyplot as plt


existing_data=pd.read_csv('C:/Users/Admin/Consumer_Dataset.csv')
test_data=pd.read_csv('C:/Users/Admin/Consumer_Test_Dataset.csv')
x=test_data

In [199]:
existing_data['Work_Experience'].fillna(existing_data['Work_Experience'].median(), inplace=True)
existing_data['Family_Size'].fillna(existing_data['Family_Size'].median(), inplace=True)
existing_data['Profession'].fillna(existing_data['Profession'].mode()[0], inplace=True)
test_data['Work_Experience'].fillna(test_data['Work_Experience'].median(), inplace=True)
test_data['Family_Size'].fillna(test_data['Family_Size'].median(), inplace=True)
test_data['Profession'].fillna(test_data['Profession'].mode()[0], inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\3032376205.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  existing_data['Work_Experience'].fillna(existing_data['Work_Experience'].median(), inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\3032376205.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  existing_data['Family_Size'].fillna(existing_data['Family_Size'].median(), inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\3032376205.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  existing_data['Profession'].fillna(existing_data['Profession'].mode()[0], inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\3032376205.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_data['Work_Experience'].fillna(test_data['Work_Experience'].median(), inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\3032376205.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_data['Family_Size'].fillna(test_data['Family_Size'].median(), inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\3032376205.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_data['Profession'].fillna(test_data['Profession'].mode()[0], inplace=True)

In [200]:
existing_data.iloc[:,[0]]=None
existing_data=existing_data.dropna(axis=1,how='all')

test_data.iloc[:,[0]]=None
test_data=test_data.dropna(axis=1,how='all')

C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\3258778924.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'None' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  existing_data.iloc[:,[0]]=None
C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\3258778924.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'None' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  test_data.iloc[:,[0]]=None

In [201]:
# Encode categorical variables
label_encoders = {}
for column in ['Gender', 'Ever_Married', 'Profession', 'Graduated', 'Energy_Consumption', 'Preferred_Renewable']:
    le = LabelEncoder()
    existing_data[column] = le.fit_transform(existing_data[column])
    test_data[column] = le.transform(test_data[column])
    label_encoders[column] = le

C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\965062585.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = le.transform(test_data[column])
C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\965062585.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = le.transform(test_data[column])
C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\965062585.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = le.transform(test_data[column])
C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\965062585.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = le.transform(test_data[column])
C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\965062585.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = le.transform(test_data[column])
C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\965062585.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = le.transform(test_data[column])

In [202]:
# Split existing data into features and target
X = existing_data.drop(columns=['Group'])
y = existing_data['Group']

# Split data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the Random Forest Classifier
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)


# Validate the model
y_pred_val = clf.predict(X_val)
accuracy = accuracy_score(y_val, y_pred_val)
print(f'Validation Accuracy: {accuracy:.2f}')

# Predict the segments for the test data
x['Predicted_Group'] = clf.predict(test_data)

Validation Accuracy: 0.48

In [203]:
x.iloc[:,[0]]=None
x=x.dropna(axis=1,how='all')
x

,Gender,Age,Ever_Married,Family_Size,Profession,Graduated,Work_Experience,Energy_Consumption,Preferred_Renewable,Predicted_Group
0,Female,36,Yes,1.0,Engineer,Yes,0.0,Low,Solar,B
1,Male,37,Yes,4.0,Healthcare,Yes,8.0,Average,Solar,C
2,Female,69,Yes,1.0,Artist,No,0.0,Low,Solar,A
3,Male,59,Yes,2.0,Executive,No,11.0,High,Solar,C
4,Female,19,No,4.0,Marketing,No,1.0,Low,Solar,D
...,...,...,...,...,...,...,...,...,...,...
2622,Male,29,No,4.0,Healthcare,No,9.0,Low,Solar,D
2623,Female,35,No,1.0,Doctor,Yes,1.0,Low,Solar,B
2624,Female,53,No,2.0,Entertainment,Yes,1.0,Low,Solar,A
2625,Male,47,Yes,5.0,Executive,Yes,1.0,High,Hydro,C
2626,Female,43,No,3.0,Healthcare,Yes,9.0,Low,Not Interested,D